version: '3.5'

services:
    ai_backend:
        build: ./backend
        container_name: ai_back
        ports: 
            - 5000:5000
        volumes: 
            - model:/src/model
        depends_on: 
            - ai_training

    ai_frontend:
        build: ./frontend
        container_name: ai_front
        ports: 
            - 3000:3000
        links:
            - ai_backend

    ai_training:
        build: ./training
        container_name: ai_train
        volumes: 
            - model:/src/model
            - images:/src/imgs        

volumes: 
    model:
    images: